#!/usr/bin/env sh

echo 'Commits'
git log --pretty=format:'' | wc -l

echo 'Contributors'
git log --pretty=short --no-merges | git shortlog -ne | egrep -ve '^ +' | egrep -ve '^$' | wc -l

echo 'Resolved bugs/feature requests'
egrep -e '^\*' History.md | wc -l

echo 'Open tickets'
curl -s https://api.github.com/repos/cucumber/cucumber/issues?state=open | ruby -e "require 'multi_json'; puts MultiJson.load(STDIN.read).length"

echo 'Group members'
curl -s http://groups.google.com/group/cukes | grep Members
