#!/usr/bin/env bash
#
# Replaces certain "uncontrollable" properties with fixed values
# This allows for comparison of documents without expecting these
# properties to be equal
#
# We also remove "output" fields for now a we are not yet
# sure how to handle that.
# Thi hould reflect in CCK
set -euf -o pipefail

jq "del(.[].elements[]?.before[]?.result.duration)" | \
jq "del(.[].elements[]?.steps[]?.result.duration)" | \
jq "del(.[].elements[]?.after[]?.result.duration)" | \
jq "del(.[].elements[]?.before[]?.output)" | \
jq "del(.[].elements[]?.steps[]?.output)" | \
jq "del(.[].elements[]?.after[]?.output)" | \
jq

