inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Exclude

require:
  - rubocop-capybara
  - rubocop-packaging
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: disable
  # Keep this inline with the lowest ruby version in the gemspec
  TargetRubyVersion: 2.7
  # Display cop name / style guide references
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'temp_app/**/*'
    - 'cck/features/**/*'

# A line length of 200 covers most violations in the repo while still being a more up to date length given today's screen sizes
Layout/LineLength:
  Max: 200

# Reviewed: Formatters put trailing spaces after things like 'Feature: '
# In pretty_spec.rb & progress_spec.rb offences look false as the trailing spaces are in fact multiline string literals
Layout/TrailingWhitespace:
  Exclude:
    - 'spec/cucumber/formatter/pretty_spec.rb'
    - 'spec/cucumber/formatter/progress_spec.rb'

# TODO: [LH] - This needs a re-review. I think we can pretty much delete / phase this out with incremental updates
# We exclude proto_world for documentation (rdoc) purpose
Lint/UselessMethodDefinition:
  Enabled: true
  Exclude:
    - 'lib/cucumber/glue/proto_world.rb'

# TODO: [LH] - Initial 10% reduction done Aug '23 - Further reductions should happen as/when we fix a bunch of the todo
# to the auto-gen-config
Metrics/AbcSize:
  Max: 41
  # TODO: Manually added! - be careful with regenning the file - this needs a fix
  Exclude:
    - lib/cucumber/formatter/junit.rb
    - spec/cucumber/formatter/http_io_spec.rb
    - lib/cucumber/glue/proto_world.rb

# TODO: [LH] - This definitely needs a partial fix / reduction. Even if only an interim one that pushes some stuff
Metrics/ClassLength:
  Max: 375
  Exclude:
    - 'lib/cucumber/cli/options.rb'
    # TODO: Manually added! - be careful with regenning the file - this needs a fix
    - lib/cucumber/formatter/pretty.rb

# TODO: [LH] - Initial 10% reduction done Aug '23 - Further reductions should happen as/when we fix a bunch of the todo
Metrics/ModuleLength:
  Max: 135
  Exclude:
    - './spec/**/*'
    # TODO: Manually added! - be careful with regenning the file - this needs a fix
    - lib/cucumber/formatter/console.rb

# TODO: [LH] - Initial 10% reduction done Aug '23 - Further reductions should happen as/when we fix a bunch of the todo
Metrics/MethodLength:
  Max: 27
  # TODO: Manually added! - be careful with regenning the file - this needs a fix
  Exclude:
    - lib/cucumber/cli/main.rb
    - lib/cucumber/cli/options.rb
    - lib/cucumber/formatter/publish_banner_printer.rb
    - spec/cucumber/formatter/http_io_spec.rb
    - lib/cucumber/glue/proto_world.rb

# Rubocop doesn't like method names in other languages but as Cucumber supports multiple languages, this cop needs to be disabled.
Naming/AsciiIdentifiers:
  Enabled: false

# For the most part, the project is solid on naming. There are though, a few
# cases where the cop doesn't need to catch.
Naming/MethodName:
  Exclude:
    - 'examples/i18n/ar/lib/calculator.rb'
    - 'examples/i18n/he/lib/calculator.rb'
    - 'lib/cucumber/glue/dsl.rb'

## In most cases, being descriptive with parameter names helps a reader understand
## what the variable is for. In some cases, shorter names are sufficient.
#Naming/MethodParameterName:
#  AllowedNames: _, e, n, v, id, io, gh, pr

# Reviewed: these offenses look false as the variables are in cyrillic
Naming/VariableName:
  Exclude:
    - 'examples/i18n/ru/features/step_definitions/calculator_steps.rb'
    - 'examples/i18n/uk/features/step_definitions/calculator_steps.rb'
    - 'examples/i18n/uz/features/step_definitions/calculator_steps.rb'

# Rubocop doesn't handle some international words well for this cop
Naming/VariableNumber:
  EnforcedStyle: normalcase
  Exclude:
    - 'examples/i18n/**/*'

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash', 'heredoc']

# Stylistic preference for cucumber
RSpec/MessageSpies:
  EnforcedStyle: receive

# Stylistic preference for cucumber
Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: annotated

# Stylistic preference for cucumber
Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
