inherit_from: .rubocop_todo.yml

AllCops:
  # Cop names are not displayed in offense messages by default. Change behavior
  # by overriding DisplayCopNames, or by giving the `-D/--display-cop-names`
  # option.
  DisplayCopNames: true
  # Style guide URLs are not displayed in offense messages by default. Change
  # behavior by overriding `DisplayStyleGuide`, or by giving the
  # `-S/--display-style-guide` option.
  DisplayStyleGuide: true
  Exclude:
    - 'tmp/**/*'
    - 'vendor/**/*'

# Reviewed: please see PR-1022 for details on why this cop is disabled: https://github.com/cucumber/cucumber-ruby/pull/1022
Lint/AmbiguousOperator:
  Enabled: False

# Reviewed: in pretty_spec.rb, progress_spec.rb offences look false,
#           as the trailing spaces are in multiline string literals
Style/TrailingWhitespace:
  Exclude:
    - 'spec/cucumber/formatter/pretty_spec.rb'
    - 'spec/cucumber/formatter/progress_spec.rb'

# Reviewed: these offenses look false as the variables are in cyrillic
Style/VariableName:
  Exclude:
    - 'examples/i18n/ru/features/step_definitions/calculator_steps.rb'
    - 'examples/i18n/uk/features/step_definitions/calculator_steps.rb'
    - 'examples/i18n/uz/features/step_definitions/calculator_steps.rb'

# Reviewed: Formatters put trailing spaces after things like 'Feature: '
Style/TrailingWhitespace:
  Exclude:
    - 'spec/cucumber/formatter/pretty_spec.rb'
    - 'spec/cucumber/formatter/progress_spec.rb'
