inherit_from: .rubocop_todo.yml

require:
  - rubocop-capybara
  - rubocop-packaging
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: disable
  # Keep this inline with the lowest ruby version in the gemspec
  TargetRubyVersion: 2.7
  # Display cop name / style guide references
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - 'bin/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'temp_app/**/*'
    - 'cck/features/**/*'

# TODO: [LH] - Candidate for phasing out in v9 patch releases. People should have this stored in editor and ideally not use windows
# for ruby development. Where they are, their editor config should have this setting
Layout/EndOfLine:
  EnforcedStyle: lf

# Reviewed: Formatters put trailing spaces after things like 'Feature: '
# In pretty_spec.rb & progress_spec.rb offences look false as the trailing spaces are in fact multiline string literals
Layout/TrailingWhitespace:
  Exclude:
    - 'spec/cucumber/formatter/pretty_spec.rb'
    - 'spec/cucumber/formatter/progress_spec.rb'

# TODO: [LH] - This needs re-reviewing and fixing, we have been partially fixing this up in 2019/2020 onwards
# (Likely that this is primarily already fixed)
# Reviewed: please see PR-1022 for details on why this cop is disabled:
# https://github.com/cucumber/cucumber-ruby/pull/1022
Lint/AmbiguousOperator:
  Enabled: false

# TODO: [LH] - This needs a re-review. I think we can pretty much delete / phase this out with incremental updates
# We exclude proto_world for documentation (rdoc) purpose
Lint/UselessMethodDefinition:
  Enabled: true
  Exclude:
    - 'lib/cucumber/glue/proto_world.rb'

# TODO: [LH] - This definitely needs a partial fix / reduction. Even if only an interim one that pushes some stuff
# to the auto-gen-config
Metrics/AbcSize:
  Max: 45

# TODO: [LH] - This needs a re-review. I think we can pretty much delete / phase this out with incremental updates
Metrics/BlockLength:
  CountComments: false
  Exclude:
    - './cucumber.gemspec'
    - './spec/**/*'
    - 'cck/spec/**/*'

# TODO: [LH] - This definitely needs a partial fix / reduction. Even if only an interim one that pushes some stuff
Metrics/ClassLength:
  Max: 375
  Exclude:
    - 'lib/cucumber/cli/options.rb'

# A line length of 200 covers most violations in the repo while still being a more up to date length given today's screen sizes
Layout/LineLength:
  Max: 200

# TODO: [LH] - This definitely needs a partial fix / reduction. Even if only an interim one that pushes some stuff
Metrics/ModuleLength:
  Max: 150
  Exclude:
    - './spec/**/*'
    - 'cck/spec/**/*'

# TODO: [LH] - This definitely needs a partial fix / reduction. Even if only an interim one that pushes some stuff
Metrics/MethodLength:
  Max: 30

# Rubocop doesn't like method names in other languages but as Cucumber supports
# languages, this cop needs to be disabled.
Naming/AsciiIdentifiers:
  Enabled: false

# For the most part, the project is solid on naming. There are though, a few
# cases where the cop doesn't need to catch.
Naming/MethodName:
  EnforcedStyle: snake_case
  Enabled: true
  Exclude:
    - 'examples/i18n/ar/lib/calculator.rb'
    - 'examples/i18n/he/lib/calculator.rb'
    - 'examples/i18n/he/lib/calculator.rb'
    - 'examples/i18n/tr/lib/hesap_makinesi.rb'
    - 'lib/cucumber/glue/dsl.rb'

# In most cases, being descriptive with parameter names helps a reader understand
# what the variable is for. In some cases, shorter names are sufficient.
Naming/MethodParameterName:
  AllowedNames: _, e, n, v, id, io, gh, pr

# Reviewed: these offenses look false as the variables are in cyrillic
Naming/VariableName:
  Exclude:
    - 'examples/i18n/ru/features/step_definitions/calculator_steps.rb'
    - 'examples/i18n/uk/features/step_definitions/calculator_steps.rb'
    - 'examples/i18n/uz/features/step_definitions/calculator_steps.rb'

# Rubocop doesn't handle some international words well for this cop
Naming/VariableNumber:
  EnforcedStyle: normalcase
  Exclude:
    - 'examples/i18n/**/*'

# This cop throws errors when parsing a lot of the repo's code, possibly due
# to splat issues?
Style/AccessModifierDeclarations:
    Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FormatStringToken:
  EnforcedStyle: annotated

Style/FloatDivision:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true
