source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'cucumber', path: '..'
gem 'protobuf-cucumber', path: ENV['PROTOBUF_CUCUMBER'] if ENV['PROTOBUF_CUCUMBER']

if ENV['CUCUMBER_RUBY_CORE']
  gem 'cucumber-core', path: ENV['CUCUMBER_RUBY_CORE']
elsif !ENV['CUCUMBER_USE_RELEASED_GEMS']
  gem 'cucumber-core', github: 'cucumber/cucumber-ruby-core', branch: 'fire-events'
end

if ENV['CUCUMBER_RUBY_WIRE']
  gem 'cucumber-wire', path: ENV['CUCUMBER_RUBY_WIRE']
elsif !ENV['CUCUMBER_USE_RELEASED_GEMS']
  gem 'cucumber-wire', github: 'cucumber/cucumber-ruby-wire'
end

if ENV['MONOREPO_PATH']
  gem 'cucumber-gherkin', path: "#{ENV['MONOREPO_PATH']}/gherkin/ruby/"
  gem 'cucumber-messages', path: "#{ENV['MONOREPO_PATH']}/messages/ruby/"
end

gem 'rspec'
