$:.unshift(File.dirname(__FILE__) + '/../../lib')
require 'cucumber/rake/task'

Cucumber::Rake::Task.new(:features) do |t|
  t.cucumber_opts = %w{--format pretty}
end

task :features => :compile

task :compile do
  sh "csc /target:library /out:Demo.dll src\\demo\\Calculator.cs"
end