name: Run Ruby tests
description: Runs Ruby tests

inputs:
  ruby-version:
    description: Version of ruby to use with ruby/setup-ruby@v1
    required: false
    default: '3.1'

runs:
  using: "composite"
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@762794c140bbeda0f1224786aa33b4b46783a6c1 # v1.326.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run tests
      run: bundle exec rake
      shell: bash
