desc 'Run features for all languages'
task :i18n do
  dir = File.dirname(__FILE__)
  Dir["#{dir}/*"].each do |f|
    if File.directory?(f)
      lang = f[dir.length+1..-1]
      if supported?(lang)
        Dir.chdir(f) do
          rake("features")
        end
      else
        STDERR.puts %{
!!!!!
!!!!! SKIPPING #{lang} (Still needs some work)
!!!!!
}
      end
    end
  end
end

def supported?(lang)
  if RUBY_VERSION =~ /^1\.9/
    !%w{ar ko zh-CN}.index(lang)
  else
    !%w{ar ko}.index(lang)
  end
end

def rake(args)
  ruby($0, args) rescue nil
end
