$:.unshift(File.dirname(__FILE__) + '/../../lib')
require 'cucumber/rake/task'

SAMPLE_FEATURE_FILE = './fixtures/self_test/features/sample.feature'

Cucumber::Rake::Task.new(:features)

task :default => :features

Cucumber::Rake::Task.new(:pass) do |t|
  t.cucumber_opts = "#{SAMPLE_FEATURE_FILE}:11"
end

Cucumber::Rake::Task.new(:fail) do |t|
  t.cucumber_opts = "#{SAMPLE_FEATURE_FILE}:17"
end
