name: Release GitHub

on:
  push:
    branches: [release/*]

jobs:
  create-github-release:
    name: Create GitHub Release and Git tag
    runs-on: ubuntu-latest
    environment: Release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        with:
          persist-credentials: false
      - uses: cucumber/action-create-github-release@cf2c6f77ba35d2424362e83393a1c4c004cf2ddb # v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
