name: Lint

permissions: {}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: ruby/setup-ruby@8e41b362d2589a22a44c1cfa214b3c83052c195b # v1.318.0
        with:
          ruby-version: '4.0.5'
          bundler-cache: true
      - run: bundle exec rubocop
